// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/auth" | "/dashboard" | "/dashboard/new" | "/project/[id]/archive" | "/project/[id]/asset-make" | "/project/[id]/assets" | "/project/[id]/i2v" | "/project/[id]/image-studio" | "/project/[id]/library/studio-image" | "/project/[id]/library/studio-video" | "/project/[id]/lipsync" | "/project/[id]/review" | "/project/[id]/root-assets" | "/project/[id]/scene-editor" | "/project/[id]/scenes" | "/project/[id]/script" | "/project/[id]/settings" | "/project/[id]/t2i" | "/project/[id]/t2v" | "/project/[id]/totaltree" | "/project/[id]/trash" | "/project/[id]/version" | "/project/[id]/video-studio" | "/project/[id]/workspace"
type AppRouteHandlerRoutes = "/api/asset-make/generate" | "/api/auth/signout" | "/api/download" | "/api/env-check" | "/api/i2v/cancel" | "/api/i2v/generate" | "/api/invitations/accept" | "/api/lipsync/generate" | "/api/projects/[id]/chat" | "/api/projects/[id]/invite" | "/api/projects/[id]/members" | "/api/projects/create" | "/api/prompts/master" | "/api/prompts/master/bulk" | "/api/prompts/optimize" | "/api/scene-editor/extract-marks" | "/api/scene-editor/snapshots" | "/api/scene-editor/snapshots/[id]" | "/api/scenes/assign" | "/api/scenes/classify" | "/api/scenes/settings" | "/api/scenes/suggest-splits" | "/api/seedance/scriptize" | "/api/t2i/edit" | "/api/t2i/generate" | "/api/t2v/freestyle" | "/api/t2v/generate" | "/api/t2v/optimize" | "/api/users/search"
type PageRoutes = never
type LayoutRoutes = "/" | "/project/[id]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/asset-make/generate": {}
  "/api/auth/signout": {}
  "/api/download": {}
  "/api/env-check": {}
  "/api/i2v/cancel": {}
  "/api/i2v/generate": {}
  "/api/invitations/accept": {}
  "/api/lipsync/generate": {}
  "/api/projects/[id]/chat": { "id": string; }
  "/api/projects/[id]/invite": { "id": string; }
  "/api/projects/[id]/members": { "id": string; }
  "/api/projects/create": {}
  "/api/prompts/master": {}
  "/api/prompts/master/bulk": {}
  "/api/prompts/optimize": {}
  "/api/scene-editor/extract-marks": {}
  "/api/scene-editor/snapshots": {}
  "/api/scene-editor/snapshots/[id]": { "id": string; }
  "/api/scenes/assign": {}
  "/api/scenes/classify": {}
  "/api/scenes/settings": {}
  "/api/scenes/suggest-splits": {}
  "/api/seedance/scriptize": {}
  "/api/t2i/edit": {}
  "/api/t2i/generate": {}
  "/api/t2v/freestyle": {}
  "/api/t2v/generate": {}
  "/api/t2v/optimize": {}
  "/api/users/search": {}
  "/auth": {}
  "/dashboard": {}
  "/dashboard/new": {}
  "/project/[id]": { "id": string; }
  "/project/[id]/archive": { "id": string; }
  "/project/[id]/asset-make": { "id": string; }
  "/project/[id]/assets": { "id": string; }
  "/project/[id]/i2v": { "id": string; }
  "/project/[id]/image-studio": { "id": string; }
  "/project/[id]/library/studio-image": { "id": string; }
  "/project/[id]/library/studio-video": { "id": string; }
  "/project/[id]/lipsync": { "id": string; }
  "/project/[id]/review": { "id": string; }
  "/project/[id]/root-assets": { "id": string; }
  "/project/[id]/scene-editor": { "id": string; }
  "/project/[id]/scenes": { "id": string; }
  "/project/[id]/script": { "id": string; }
  "/project/[id]/settings": { "id": string; }
  "/project/[id]/t2i": { "id": string; }
  "/project/[id]/t2v": { "id": string; }
  "/project/[id]/totaltree": { "id": string; }
  "/project/[id]/trash": { "id": string; }
  "/project/[id]/version": { "id": string; }
  "/project/[id]/video-studio": { "id": string; }
  "/project/[id]/workspace": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/project/[id]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
