// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../src/app/auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/archive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/archive">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/archive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/asset-make/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/asset-make">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/asset-make/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/assets">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/i2v/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/i2v">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/i2v/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/image-studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/image-studio">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/image-studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/library/studio-image/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/library/studio-image">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/library/studio-image/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/library/studio-video/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/library/studio-video">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/library/studio-video/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/lipsync/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/lipsync">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/lipsync/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/review">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/root-assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/root-assets">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/root-assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/scene-editor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/scene-editor">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/scene-editor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/scenes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/scenes">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/scenes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/script/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/script">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/script/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/settings">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/t2i/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/t2i">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/t2i/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/t2v/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/t2v">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/t2v/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/totaltree/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/totaltree">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/totaltree/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/trash/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/trash">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/trash/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/version/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/version">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/version/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/video-studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/video-studio">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/video-studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]/workspace">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/asset-make/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/asset-make/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/asset-make/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/signout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/signout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/download">> = Specific
  const handler = {} as typeof import("../../src/app/api/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/env-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/env-check">> = Specific
  const handler = {} as typeof import("../../src/app/api/env-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/i2v/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/i2v/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/api/i2v/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/i2v/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/i2v/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/i2v/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/invitations/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invitations/accept">> = Specific
  const handler = {} as typeof import("../../src/app/api/invitations/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/lipsync/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lipsync/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/lipsync/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/invite">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/members">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/prompts/master/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/prompts/master/bulk">> = Specific
  const handler = {} as typeof import("../../src/app/api/prompts/master/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/prompts/master/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/prompts/master">> = Specific
  const handler = {} as typeof import("../../src/app/api/prompts/master/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/prompts/optimize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/prompts/optimize">> = Specific
  const handler = {} as typeof import("../../src/app/api/prompts/optimize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/scene-editor/extract-marks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scene-editor/extract-marks">> = Specific
  const handler = {} as typeof import("../../src/app/api/scene-editor/extract-marks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/scene-editor/snapshots/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scene-editor/snapshots/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/scene-editor/snapshots/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/scene-editor/snapshots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scene-editor/snapshots">> = Specific
  const handler = {} as typeof import("../../src/app/api/scene-editor/snapshots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/scenes/assign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scenes/assign">> = Specific
  const handler = {} as typeof import("../../src/app/api/scenes/assign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/scenes/classify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scenes/classify">> = Specific
  const handler = {} as typeof import("../../src/app/api/scenes/classify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/scenes/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scenes/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/scenes/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/scenes/suggest-splits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scenes/suggest-splits">> = Specific
  const handler = {} as typeof import("../../src/app/api/scenes/suggest-splits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/seedance/scriptize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seedance/scriptize">> = Specific
  const handler = {} as typeof import("../../src/app/api/seedance/scriptize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/t2i/edit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/t2i/edit">> = Specific
  const handler = {} as typeof import("../../src/app/api/t2i/edit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/t2i/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/t2i/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/t2i/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/t2v/freestyle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/t2v/freestyle">> = Specific
  const handler = {} as typeof import("../../src/app/api/t2v/freestyle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/t2v/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/t2v/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/t2v/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/t2v/optimize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/t2v/optimize">> = Specific
  const handler = {} as typeof import("../../src/app/api/t2v/optimize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/project/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
